### ISSUE TITLE
[Feature Request] Pull for several users

### ISSUE THREAD

**Issue by jodom1979** [BoxThatBeat/obsidian-agile-task-notes#11]
Thanks for the plugin! Been using it daily. 

I need to see several users tasks within a sprint. Would we be able to enter a comma separated list of users?  

Thanks!

**Comment by BoxThatBeat** [comment]
Good idea, will look into it! Thanks!

**Comment by BoxThatBeat** [comment]
@jodom1979 I am currently working on this and am half way done in the branch pull-for-additional-users

**Comment by mtuckerb** [comment]
might I suggest a wildcard for all users. Our PM would like to use this for the whole team.

**Comment by jodom1979** [comment]
Oh my, yes this would be amazing!

Thanks for putting this together, it will be used heavily.

Best regards,

-J

**Comment by BoxThatBeat** [comment]
@mtuckerb Good idea! I'll add a toggle switch for "Team Leader Mode" which will get all users of the team. I am still working on the Kanban board mode but when I am done that I will continue work on this feature!

**Comment by BoxThatBeat** [comment]
@jodom1979, @mtuckerb I have completed this feature and it is in the latest release (1.2.0). Try it out and let me know what you think! @mtuckerb, your PM can use the new "Team Leader Mode" toggle in the settings to get all user's tasks

**Comment by jodom1979** [comment]
This is such a massive improvement! Thank you for all the hard work, it will be used everyday. 

I can specify individual usernames in a comma separated list just fine, and that works well. However, for Team Leader mode, I do get an error. I might be doing something wrong, but wanted to check with you. 

TypeError: Cannot read properties of null (reading 'displayName')
    at eval (plugin:obsidian-agile-task-notes:329:162)
    at Array.forEach (<anonymous>)
    at eval (plugin:obsidian-agile-task-notes:328:39)
    at Array.forEach (<anonymous>)
    at JiraClient.eval (plugin:obsidian-agile-task-notes:327:29)
    at Generator.next (<anonymous>)
    at fulfilled (plugin:obsidian-agile-task-notes:27:24)
    
![Screenshot 2023-03-09 164720](https://user-images.githubusercontent.com/1341041/224167763-1b606b20-5aa8-42ea-91c5-7eccb046d2cf.png)

**Comment by BoxThatBeat** [comment]
@jodom1979 thanks for submitting this error. It brings up a point I had not thought of. The current implementation I added for this teamleader mode will pull all tasks even if they are not assigned to anyone (which is what is causing the error). I am not sure what the preferred behavior would be for team leaders, do you have a preference? Should it:
1. Pull all tasks even if they are assigned to nobody
2. Only pull tasks that are at least assigned to somebody

**Comment by mtuckerb** [comment]
If you go with option 1, option 2 could at least be handled by an aggressive include list on the list of users to include feature.

**Comment by jodom1979** [comment]
For our purposes, tasks remain unassigned only in backlog. We'll typically
not add a task to an active sprint without them being assigned to someone.
So in my case, I think option 2, but I could see both being used depending
on someone's circumstance.

So far though, the integration is fantastic! This will only make it better!
Thanks again Tucker!

-Jake

**Comment by BoxThatBeat** [comment]
Should be fixed now @jodom1979. I decided to allow tasks with no assignees for team leader mode since you can still opt to exclude the backlog which has most of those tasks anyways. Hope it benefits you guys!
