### ISSUE TITLE
Allow task "Description" as a initial task content variable

### ISSUE THREAD

**Issue by henrikje** [BoxThatBeat/obsidian-agile-task-notes#12]
It would be helpful to have the "Description" field available as a `{{TASK_DESCRIPTION}}` variable specifying the "initial task content" template.

**Comment by henrikje** [comment]
And ideally "Acceptance Criteria" too. :-)

**Comment by BoxThatBeat** [comment]
That is a good idea, thank you! I'll add the task description as a field. I don't believe the "Acceptance Criteria" field is a default one and thus would not be simple to implement. I could perhaps implement custom fields by having a comma separated text field that was the names of the custom fields and then have the user be able to place those in the template, but that is a new feature altogether so I won't implement that quite yet. Feel free to make a new issue for custom fields though!

**Comment by BoxThatBeat** [comment]
@henrikje I've finished implementing this, it is included in release 1.0.5!
