### ISSUE TITLE
[Feature Request] Add task "Assigned To" field

### ISSUE THREAD

**Issue by ssenart** [BoxThatBeat/obsidian-agile-task-notes#4]
Great plugin ! Thanks !

Currently, we have all the tasks of the team. Fine.

Could it be possible to add the task field "Assigned To" so we can filter and have only my tasks or being able to organize tasks by assignee.

Also, for note template substitution, would it be possible to add patterns: {{TASK_ID}}, {{TASK_STATE}}, {{TASK_ASSIGNEDTO}}.

**Comment by BoxThatBeat** [comment]
Thanks for implementing this! A way you could filter tasks would be to add the {{TASK_ASSIGNEDTO}} variable as metadata to the new task notes and then use the Dataview plugin to aggregate the tasks.
