### ISSUE TITLE
[Contribution] Using Jira without sprints

### ISSUE THREAD

**Issue by froznsm** [BoxThatBeat/obsidian-agile-task-notes#7]
First of all, thanks for this plugin!! It has been very useful as a base for what I have done. 
My use-case was slightly different to the one this plugin was built for:
For me, Jira is used purely as a Kanban board without sprints. I have modified the plugin to work accordingly:
- All issues on the configured board that are assigned to the configured user and that fall within a specific status are pulled and the notes created
- The notes for all issues that have one of the final states (like `dont` or `won't do`) are moved to a final folder.
- The same could be done to issues in other states

Are you interested at all in me adding some variant of this functionality to this repo? If so, how would you want the configuration to look?! If this is out of scope I fully understand.

I figure it works for me, maybe it works for somebody else too. 
Once again thanks for your work!

**Comment by NitroDesignsSk** [comment]
Count me as one of those people this would work for and would love to see.

**Comment by DevBOFH** [comment]
Add me to the list here. My team also uses Jira Kanban, without sprints.

**Comment by BoxThatBeat** [comment]
@froznsm Would you still like to add this functionality as an alternate mode to the current functionality? I could have a go at implementing it if you don't have the time.

**Comment by froznsm** [comment]
Thanks for asking! I will try and get a draft ready in the next weeks. If I do not get anything done by then, I'll pass it over back to you

**Comment by froznsm** [comment]
Hey everybody! I have started to work on this and id like your opinion on a little UX problem I have encountered.

The intended functionality is differentiating between _create-note_ issue states (e.g. "In Progress") and _final_ issue states (e.g. "Done"). As issue states and columns are board specific, these states have to be configurable for this plugin. No matter how exactly the state-selection is implemented, there will have to be two of them.
I have gone through a few iterations of how the settings for this could look:

- The easiest to build, but error prone and shitty UX option is a textfield. We could display all configured state for a board and let the user type in the ones they want to have created notes for as well as the ones they consider final.
- I played around with creating toggles per state. In theory it seems alright, but you cannot display text in front of each toggle with the default functionality. You could create a new setting per toggle, but this will make the settings tab extremely long and unusable. 
- The best option is a multi-select dropdown, but this is not supported out of the box. Now, the API gives you the tools to modify the actual underlying HTML elements of the settings, so anything is possible in theory. I have tried figuring this out, but as I have almost no frontend experience to speak of, this will take me a while (though I enjoy the challenge of it). 

Do you see any other options? Do you have any thoughts on this?

**Comment by BoxThatBeat** [comment]
Hey @froznsm! I think for now you can just do a simple text field with comma separated values. Improving upon the UI can be a future task. If you have a look at the AzureDevops settings, you'll see I used that method for the names of the columns haha. I think I am also going to add a comma separated text field for a multi-user note pulling (as requested by others). So there will be quite a few of these comma separated text fields and so we can just replace them altogether at a later date if desired. Thanks for taking this task on!

**Comment by BoxThatBeat** [comment]
@froznsm, @NitroDesignsSk, @bcwilsondotcom happy to say this feature has been release in the new version of the plugin 1.1.0! Feel free to give feedback in the discussions tab. 😄
