### ISSUE TITLE
error while updating sprint

### ISSUE THREAD

**Issue by dasJoschi** [BoxThatBeat/obsidian-agile-task-notes#8]
Hello, 
I'm pretty new to obsidian and would like to use the plugin.

When I update (manually via update sprint command). I get an error with hint to the developer console (see below) and no kanban board has been created. I think it could be the proxy settings but not sure how to check or change them in obsidian (system settings are correct and working fine).

I configured the plugin according to the readme (strict mode off, kanban and todo plugin, server, name, mail, token, board-id).

When I start obsidian (pretty empty and new) this is the full console output:

```
- app.js:1 Obsidian Developer Console
    node:electron/js2c/renderer_init:89 Electron Security Warning (Insecure Content-Security-Policy) This renderer process has either no Content Security
      Policy set or a policy with "unsafe-eval" enabled. This exposes users of
      this app to unnecessary security risks.
    
    For more information and help, consult
    https://electronjs.org/docs/tutorial/security.
    This warning will not show up
    once the app is packaged.
- warnAboutInsecureCSP @ node:electron/js2c/renderer_init:89
- plugin:obsidian-admonition:479 Obsidian Admonition loaded
- plugin:table-editor-obsidian:23712 loading markdown-table-editor plugin
- plugin:obsidian-advanced-slides:318 server started at http://localhost:3000
- plugin:nldates-obsidian:9043 Loading natural language date parser plugin
- DevTools failed to load source map: Could not load content for app://obsidian.md/luxon.js.map: System error: net::ERR_FILE_NOT_FOUND
- plugin:obsidian-plugin-todo:9801 [obsidian-plugin-todo] Parsed 3 TODOs from 3 markdown files in (0.231s)
- plugin:obsidian-agile-task-notes:59 Error: net::ERR_TUNNEL_CONNECTION_FAILED
    at SimpleURLLoaderWrapper.<anonymous> (node:electron/js2c/browser_init:101:7169)
    at SimpleURLLoaderWrapper.emit (node:events:390:28)
```

Can you help me out?

**Comment by BoxThatBeat** [comment]
Hello,

Are you using the newest version of Obsidian? I have not seen this error before, it looks like it mentions tunneling. Are you perhaps running Obsidian on a VM or on a VPN network?

**Comment by dasJoschi** [comment]
Yes my entire System is an remote access VM and the Host is in an other network than the jira server and the networks are secured via vpn, so no vpn direktly on my VM or the Host. 
On my VM Jira is "pingable" and reachable via different browsers wich use my system proxy and network settings.

I will ask a coworker with an machine within the network to try obsidian and your plugin with our jira. 

Can I configure certificates/proxy settings within obsidian or the plugin?

Thank you for the fast reply.
